// <auto-generated />
namespace BookStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addnewtableorder4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewtableorder4));
        
        string IMigrationMetadata.Id
        {
            get { return "202404140417266_add-new-table-order-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
